# Generated by Django 5.0.1 on 2024-03-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0002_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='title',
        ),
    ]
