# Generated by Django 5.0.1 on 2024-03-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0003_remove_suggestion_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_details',
        ),
        migrations.AddField(
            model_name='packagepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packagepayment',
            name='pesapal_transaction_tracking_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagepayment',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pesapal_transaction_tracking_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
