# Generated by Django 5.0.1 on 2024-03-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0004_remove_ticket_passenger_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pesapal_transaction_tracking_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger_name',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
