# Generated by Django 5.0.1 on 2024-01-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarked',
        ),
    ]
