# Generated by Django 4.1.3 on 2024-03-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
